### ISSUE TITLE
Config file to use along with plugin

### ISSUE THREAD

**Issue by pouyayarandi** [dfed/SafeDI#147]
**Goals**
Plugin uses a config file to customize code generation with minimum effort.

**Investigations**
I used `safe-di-tool` cli directly but it was a little challenging to setup.

**Design**
Add a `.safedi.yml` file in root directory and add configs to it like below:
```yaml
- include:
  - MainApp
  - Packages
- additional-imported-modules:
  - SomeRandomLibrary
```
SafeDI plugin read this file and set arguments.
If there is no yml file with this name in root directory, do default behavior.
